[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ctrlutils"
version = "1.5.0"
authors = [
    {name = "Toki Migimatsu", email = "takatoki@cs.stanford.edu"}
]
description = "Python robot control utils"
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = ["numpy", "redis"]

[project.urls]
Homepage = "https://github.com/tmigimatsu/ctrl-utils.git"

[tool.semantic_release]
branch = "main"
build_command = false
upload_to_repository = false
upload_to_release = false
version_variable = ["setup.py:__version__", "ctrlutils/__init__.py:__version__"]
version_pattern = ["CMakeLists.txt:VERSION {version}$"]
version_toml = ["pyproject.toml:project.version"]

[tool.cibuildwheel]
skip = ["cp36-*", "pp*", "*-musllinux*"]

[tool.cibuildwheel.linux]
archs = ["auto64"]

[tool.cibuildwheel.macos]
archs = ["universal2"]

[tool.cibuildwheel.macos.environment]
CMAKE_OSX_ARCHITECTURES = "arm64;x86_64"
MACOSX_DEPLOYMENT_TARGET = "10.14"
